### PR TITLE
Spreads the Hair-Tying Love

### PR DESCRIPTION
**Pull request by cebutris**
All species may now access the Tie-Hair verb!

It still only works with hair with the tie-able flag so non-human hairstyles may not be able to be tied properly.

Big thanks to @fludd12 for putting up with my shit and helping with this

### CODE REVIEW

**Comment by cebutris** [comment]
Currently it gives this verb to humans regardless of whether or not they have hair that's tieable. If the hair isn't tieable it gives this message: `Your hair isn't long enough to tie.`

https://github.com/VulpesLegan/MITHRAStation/blob/master/code/modules/mob/living/carbon/human/human_powers.dm#L17.

**Comment by cebutris** [comment]
I've been looking for where hair is handled to make it so it only gives it if you have tiable hair but for the life of me I cannot find where that is

**Comment by Michiyamenotehifunana** [comment]
Each hairstyle has an associated list of flags. You'd need some sort of code that checks every mob's hairstyle for the tieable flag on spawn, and everytime a mob's hairstyle is changed.

Honestly, just having it throw an exception on untieble hairs is fine.

**Comment by Michiyamenotehifunana** [comment]
Waaaitaminute, the list of hairs the verb gives *already* is sanitized to not display untieable hairs.

**Comment by cebutris** [comment]
Currently, all humans (and custom races with human base) get the Tie-Hair verb. This allows them to change their hair from a tieable hairtype to another tieable hair type. They get this verb regardless of if their hair is tieable or not, but trying to use it with hair that isn't tieable gives a message that says it cannot be used

The PR in this current state gives the verb to ALL races. It will still function in the same way- still giving messages if the hair isn't tieable. I was asked to do this by Archon.

@EvilJackCarver wanted me to change it so that it only gives the verb if the hair is already tieable. I've been looking for where hair is handled to do this, but I haven't been able to find it.

**Comment by HawkerTheGreat** [comment]
If its already this way by default, I don't see any reason not to just add it to all races and let it be till we can properly figure out what do with it.

**Comment by cebutris** [comment]
This can be closed or merged as you see fit. I'm unlikely to put any more work into it. Working on other projects. Sorry!

**Comment by EvilJackCarver** [comment]
I'm going to go ahead and close this, then. If, later down the line, you feel the need to reopen it, let me know and I'll do so.

**Pull request closed without merging**
